---
- package:
    state: present
    name: nginx

- template:
        src: status.txt.j2
        dest: /etc/nginx/status.txt

- template:
        src: nomnom.conf.j2
        dest: /etc/nginx/nginx.conf

- name: start nginx
  shell: df -h >> /etc/nginx/status.txt

- name: start nginx
  shell: nginx
   
    